name: uprt
description: A tool to migrate static leases between DD-WRT, OpenWrt, OPNsense, Mikrotik, and pfSense routers. Also supports csv and json.
version: 2021.09.001

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  args: ^2.1.1
  path: ^1.8.0
  xml: ^5.1.2
  glob: ^2.0.1
  validators: ^3.0.0 # change to latest version

dev_dependencies:
  effective_dart: ^1.3.1
  test: ^1.17.5
  yaml: ^3.1.0
