name: uprt
description: A tool to migrate static leases between DD-WRT, OpenWrt, OPNsense, Mikrotik, and pfSense routers. Also supports csv and json.
version: 2021.10.001

environment:
  sdk: ">=2.14.2 <3.0.0"

dependencies:
  args: ^2.3.0  # BSD-3-Clause License 
  path: ^1.8.0 #BSD-3 Clause
  xml: ^5.3.0 #MIT
  glob: ^2.0.1  #BSD-3 Clause
  validators: ^3.0.0 

dev_dependencies:
  effective_dart: ^1.3.2
  flutter_lints: ^1.0.4
  test: ^1.17.12
  yaml: ^3.1.0