name: uprt
description: A tool to migrate static leases between DD-WRT, OpenWrt, OPNsense, Mikrotik, and pfSense routers. Also supports csv and json.
version: 2025.02.019

environment:
  sdk: ">=2.14.2 <3.7.1"

dependencies:
  args: ^2.3.0  # BSD-3-Clause License 
  path: ^1.8.0 #BSD-3 Clause
  xml: ^6.5.0 #MIT
  glob: ^2.0.1  #BSD-3 Clause
  validators: ^3.0.0 
  mockito: ^5.4.5

dev_dependencies:
  
  flutter_lints: ^5.0.0
  test: ^1.17.12
  yaml: ^3.1.0